name: woocommerce_flutter_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  dio: ^5.4.1
  faker: ^2.1.0
  flutter_secure_storage: ^4.2.1
  pretty_dio_logger: ^1.3.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
